### ISSUE TITLE
How do I use my own back/next/finish buttons?

### ISSUE THREAD

**Issue by iangu48** [danilrafiqi/react-native-stepper-ui#4]
Simply setting the "active" state of the parent component does not change the appearance of the steppers. How can I implement this?

**Comment by danilrafiqi** [comment]
thanks for comment, i will update the logic the package for support this pull request

**Comment by FranciscoVeracoechea** [comment]
Is there any update on this one?

**Comment by fveracoechea** [comment]
It looks like this issue is fixed: https://github.com/danilrafiqi/react-native-stepper-ui/pull/8

**Comment by dcr31000** [comment]
This issue is fixed by #8 but this update are not on npm.
Is it possible to push a new package on npm please ? (see https://www.npmjs.com/package/react-native-stepper-ui)

**Comment by isekaimaou1109** [comment]
Still not fix. i have customed the next and back buttons, the step content has changed (pass), but the stepper has not changed. And only stay at the step 1, although the "active" props has changed. Can you help me fix this bug? Thanks
